# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='projects',
            field=models.ManyToManyField(related_name='meeting_members', to='projects.Project'),
        ),
    ]
